// Package openapi3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package openapi3

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TaskStatus.
const (
	Completed TaskStatus = "completed"
	Pending   TaskStatus = "pending"
)

// Defines values for TokenType.
const (
	Bearer TokenType = "Bearer"
)

// Defines values for PostTokenJSONBodyGrantType.
const (
	ClientCredentials PostTokenJSONBodyGrantType = "client_credentials"
)

// CreateOrUpdateTaskRequest defines model for CreateOrUpdateTaskRequest.
type CreateOrUpdateTaskRequest struct {
	Description string     `json:"description"`
	Status      TaskStatus `json:"status"`
	Title       string     `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Task defines model for Task.
type Task struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description string             `json:"description"`
	ID          openapi_types.UUID `json:"id"`
	Status      TaskStatus         `json:"status"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// TokenType defines model for TokenType.
type TokenType string

// TaskId defines model for taskId.
type TaskId = openapi_types.UUID

// PostTokenJSONBody defines parameters for PostToken.
type PostTokenJSONBody struct {
	// GrantType Tells the token endpoint to perform the Client Credentials flow
	GrantType PostTokenJSONBodyGrantType `json:"grant_type"`

	// Scope Space separated string of scopes the client is requesting access to
	Scope *string `json:"scope,omitempty"`
}

// PostTokenParams defines parameters for PostToken.
type PostTokenParams struct {
	// Authorization Basic Auth header with client_id and client_secret
	Authorization string `json:"Authorization"`
}

// PostTokenJSONBodyGrantType defines parameters for PostToken.
type PostTokenJSONBodyGrantType string

// PostTasksJSONRequestBody defines body for PostTasks for application/json ContentType.
type PostTasksJSONRequestBody = CreateOrUpdateTaskRequest

// PutTasksTaskIdJSONRequestBody defines body for PutTasksTaskId for application/json ContentType.
type PutTasksTaskIdJSONRequestBody = CreateOrUpdateTaskRequest

// PostTokenJSONRequestBody defines body for PostToken for application/json ContentType.
type PostTokenJSONRequestBody PostTokenJSONBody
