// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package clients

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetByID(ctx context.Context, id uuid.UUID) (Client, error)
}

var _ Querier = (*Queries)(nil)
