// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package clients

import (
	"context"

	"github.com/google/uuid"
)

const getByID = `-- name: GetByID :one
SELECT id, secret, created_at, updated_at FROM clients
WHERE id = ? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.queryRow(ctx, q.getByIDStmt, getByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Secret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
