// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package tasks

import (
	"time"

	"github.com/google/uuid"
	"github.com/pietervdwerk/tasksapi/pkg/openapi3"
)

type Task struct {
	ID          uuid.UUID           `json:"id"`
	Title       string              `json:"title"`
	Description string              `json:"description"`
	Status      openapi3.TaskStatus `json:"status"`
	CreatedAt   time.Time           `json:"created_at"`
	UpdatedAt   time.Time           `json:"updated_at"`
}
